yatube/about/urls.py
from django.urls import path

from . import views

app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path

from . import views

app_name = 'posts'

urlpatterns = [
    path('', views.index, name='home_page'),
    path('group/<slug:slug>/', views.group_posts, name='group_list'),
    path('', views.index, name='index'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('create/', views.post_create, name='post_create'),
    path(
        'posts/<int:post_id>/comment/',
        views.add_comment, name='add_comment'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

yatube/yatube/urls.py
from django.conf import settings
from django.conf.urls.static import static
# yatube/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    # импорт правил из приложения posts
    path('auth/', include('users.urls')),
    path('', include('posts.urls', namespace='posts')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
    path('about/', include('about.urls', namespace='about')),
    path('auth/', include('users.urls', namespace='user')),
    path('group/', include('posts.urls', namespace='group')),
]


handler404 = 'core.views.page_not_found'
handler500 = 'core.views.server_error'
handler403 = 'core.views.permission_denied'
# Переопределяем Хендлер, передаем имя собственной view-функции.

if settings.DEBUG:
    # В режиме DEBUG=True должен брать картинки из директории, в MEDIA_ROOT
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/posts/models.py
from core.models import CreatedModel
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()

LENGTH_TEXT = 15
"""Количество символов"""


class Group (models.Model):
    """ Страница со списком постов."""
    title = models.CharField(max_length=200, verbose_name='Заголовок',)
    slug = models.SlugField(max_length=200, unique=True,)
    description = models.TextField(verbose_name='Описание группы',)

    def __str__(self):
        return self.title

    class Meta:
        """Переопределение Meta."""
        verbose_name = 'Группы'
        verbose_name_plural = 'Группы'


class Post(CreatedModel, models.Model):
    """ Главная страница."""
    text = models.TextField(
        verbose_name='Текст поста',
        help_text='Напишите содержимое поста',
        max_length=300, )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        verbose_name='Автор поста',
        related_name='posts')
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Здесь можно выбрать группу',
        related_name='posts')

    image = models.ImageField(
        verbose_name='Картинка',
        help_text='Здесь можно добавить картинку',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        """Переопределение Meta."""
        verbose_name = 'Посты авторов'
        verbose_name_plural = 'Посты авторов'
        ordering = ['-created']

    def __str__(self):
        return self.text[:LENGTH_TEXT]


class Comment(models.Model):
    """Класс для комментирования записей."""

    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='запись'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор'
    )
    text = models.TextField(
        'Текст',
        help_text='Текст нового комментария'
    )
    created = models.DateTimeField(
        auto_now_add=True,
        verbose_name='Дата публикации',
        db_index=True
    )

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'
        ordering = ('-created',)

    def __str__(self):
        return self.text[:LENGTH_TEXT]


class Follow(models.Model):
    """Параметры добавления новых подписок."""

    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following'
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'
        constraints = [
            models.UniqueConstraint(
                fields=('user', 'author'),
                name='unique_list'),
            models.CheckConstraint(
                check=~models.Q(user=models.F('author')),
                name='author'
            )
        ]

    def __str__(self):
        return f"Подписчик: '{self.user}' на автора: '{self.author}'"

yatube/posts/forms.py
from django import forms
from django.core.exceptions import ValidationError

from .models import Comment, Post


class PostForm(forms.ModelForm):
    """ Форма поста."""
    class Meta:
        model = Post
        fields = ('text', 'group', 'image', )


def clean_text(self):
    text = self.cleaned_date['text']
    if len(text) > 300:
        raise ValidationError('Длина текста больше 300 символов')
    return text


class CommentForm(forms.ModelForm):
    """ Форма комментария."""
    class Meta:
        model = Comment
        fields = ('text',)

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.cache import cache_page
from posts.utils import get_page

from .forms import CommentForm, PostForm
from .models import Follow, Group, Post, User

NUMBER_OF_POSTS = 10


def group_posts(request, slug):
    """ Страница со списком постов."""
    group = get_object_or_404(Group, slug=slug)
    posts = group.posts.all()
    page_obj = get_page(request, posts)
    context = {
        'group': group,
        'page_obj': page_obj,
    }
    return render(request, 'posts/group_list.html', context)


@cache_page(20, key_prefix='index_page')
def index(request):
    """Главная страница."""
    posts = Post.objects.all()
    page_obj = get_page(request, posts)
    context = {
        'page_obj': page_obj
    }
    return render(request, 'posts/index.html', context)


def post_detail(request, post_id):
    """Детали по посту."""
    template = 'posts/post_detail.html'
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    comments = post.comments.all()
    context = {
        'posts': post,
        'form': form,
        'comments': comments
    }
    return render(request, template, context)


@login_required
def add_comment(request, post_id):
    """ Функцию для обработки отправленного комментария."""
    post = get_object_or_404(Post, pk=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def post_create(request):
    """Создание нового поста."""
    form = PostForm(request.POST or None)
    if request.method == 'POST':
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', post.author)
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    """Редактирование текущего поста."""
    template = 'posts/create_post.html'
    post = get_object_or_404(Post, id=post_id)
    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        post = form.save()
        return redirect('posts:post_detail', post_id=post.id)
    context = {
        'form': form,
        'post': post,
        'is_edit': True
    }
    return render(request, template, context)


def profile(request, username):
    """ Профиль автора."""
    author = get_object_or_404(User, username=username)
    post_list = author.posts.select_related('group')
    page_obj = get_page(request, post_list)
    following = False
    if request.user.is_authenticated:
        following = request.user.follower.filter(
            author=User.objects.get(username=author)).count()
    context = {'author': author,
               'page_obj': page_obj,
               'posts_count': post_list.count,
               'following': following,
               }
    return render(request, 'posts/profile.html', context)


@login_required
def follow_index(request):
    """ Информация о текущем пользователе."""
    user = request.user
    post_list = Post.objects.filter(author__following__user=request.user)
    page_obj = get_page(request, post_list)
    context = {'username': user,
               'page_obj': page_obj,
               }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    """ Подписаться на автора."""
    user = request.user
    author = get_object_or_404(User, username=username)
    if user != author:
        Follow.objects.get_or_create(user=user, author=author)
    return redirect('posts:profile', username=username)


@login_required
def profile_unfollow(request, username):
    """ Дизлайк, отписка."""
    user = request.user
    author = get_object_or_404(User, username=username)
    follow_to_delete = get_object_or_404(
        Follow,
        user=user,
        author=author
    )
    follow_to_delete.delete()
    return redirect('posts:profile', username=username)

yatube/templates/posts/create_post.html
{% extends 'base.html' %}
{% load user_filters %}

{% block title %}Новый пост{% endblock title %}

{% block content %}
<main>
  <div class="container py-5">
    <div class="row justify-content-center">
      <div class="col-md-8 p-5">
        <div class="card">
          <div class="card-header">
            {% if is_edit %}
            Редактировать запись
            {% else %}
            Добавить запись
            {% endif %}
          </div>
          <div class="card-body">
            {% load user_filters %}
            {% if form.errors %}
              {% for field in form %}
                {% for error in field.errors %}
                  <div class="alert alert-danger">
                    {{ error|escape }}
                  </div>
                {% endfor %}
              {% endfor %}
              {% for error in form.non_field_errors %}
                <div class="alert alert-danger">
                  {{ error|escape }}
                </div>
              {% endfor %}
            {% endif %}
            <form method="post" enctype="multipart/form-data">
            {% if is_edit %}
              {% url 'posts:post_edit' post.id %}
            {% else %}
              {% url 'posts:post_create'%}
            {% endif %}">
              {% csrf_token %}
          {% for field in form %}
          <div class="form-group row my-3 p-3">
            <label for="{{ field.id_for_label }}">
              {{ field.label }}
              {% if field.field.required %}
                <span class="required text-danger">*</span>
              {% endif %}
            </label>
            {{ field|addclass:'form-control' }}
            {% if field.help_text %}
              <small id="{{ field.id_for_label }}-help" class="form-text text-muted">
                {{ field.help_text|safe }}
              </small>
            {% endif %}
          </div>
          {% endfor %}
                <small id="id_group-help" class="form-text text-muted">
                  Группа, к которой будет относиться пост
                </small>
              </div>
              <div class="d-flex justify-content-end">
                <button type="submit" class="btn btn-primary">
                  {% if is_edit %}
                    Сохранить
                  {% else %}
                    Добавить
                  {% endif %}
                </button>
              </div>
            </form>
</main>
{% endblock content %}

yatube/templates/posts/follow.html
{% extends 'base.html' %}
{% block title %} Подписаны на авторв {% endblock %}
{% block content %}
  {% for post in page_obj %}
  {% include 'posts/includes/switcher.html' %}
  {% include 'posts/includes/post_list.html' %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endblock %} 

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block content %}

<div class ="container py-5">  
    {% block header %}
    <h1>{{ group.title }}</h1>
    {% endblock %}
    <p>{{group.description}}</p>
    {% for post in page_obj %}
        <ul>
            <li>
                Автор: {{ post.author.get_full_name }}
                <a href="{% url "posts:profile" post.author %}"> Все посты пользователя</a>
            </li>
            <li>
                Дата публикации: {{ post.created|date:"d E Y" }}
            </li>
        </ul>
        {% thumbnail post.image "960x339" crop="30%" upscale=True as im %}
        <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %} 
        <p>{{ post.text }}</p>
        <a href="{% url 'posts:post_detail' post.id %}">
            Подробная информация 
        </a> 
        <p> 
        </p> 
        {% if post.group %}
        <a href="{% url 'posts:group_list' post.group.slug %}">Все записи группы</a>
        {% endif %}
        {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    {% include 'posts/includes/paginator.html' %}
</div>
{% endblock %}

yatube/templates/posts/index.html
{% extends 'base.html' %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}
{% load cache %}
{% cache 5 sidebar %}
  {% for post in page_obj %}
  {% include 'posts/includes/post_list.html' %}
  {% include 'posts/includes/switcher.html' %}
    {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
{% endcache %}
{% endblock %} 

yatube/templates/posts/post_detail.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %} Пост: {{ posts.text|truncatechars:30 }}
{% endblock %}
{% block content %}

<div class="row">
  <aside class="col-12 col-md-3">
    <ul class="list-group list-group-flush">
      <li class="list-group-item">
        <h6>Профиль пользователя: {{ posts.author }}</h6>
      </li>
      <li class="list-group-item">
        Дата публикации: {{ posts.created|date:"d E Y" }}
      </li>
      <li class="list-group-item">
        Группа: {{ posts.group.title}}
      </li>
      <li class="list-group-item">
        Автор: {{ posts.author.get_full_name }}
      </li>
      <li class="list-group-item d-flex justify-content-between align-items-center">
        Всего постов автора: {{ posts.author.posts.count }}
      </li>
      <li class="list-group-item">
        <a href="{% url "posts:profile" posts.author.username %}">
        Все посты пользователя
        </a>
      <li>
      </li>
      </li>
      
    </ul>
  </aside>
  <article class="col-12 col-md-9">
    {% thumbnail posts.image "666x646" crop="center" upscale=True as im %}
    <img style="margin:{{ im|margin:"666x646" }}" src="{{ im.url }}" width="{{ im.x }}" height="{{ im.y }}">
    {% endthumbnail %}
    <p> {{ posts.text }}</p>
    <a class="btn btn-primary" href="{% url 'posts:post_edit' posts.id %}">
      Редактировать пост
    </a>
    {% include 'posts/includes/comment.html' %}
  </article>
  {% if request.user == posts.author %}
  <div class="container py-5">
</div>
  {% endif %}
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %} 
  Профайл пользователя: {{ author }}
{% endblock %}
{% block content %}
<div class ="container py-5">
  <h2>Все посты пользователя: {{ author }} </h2>
  <h4>Всего постов: {{ page_obj.paginator.count  }} </h4>
  <div class="mb-5">
    {% if following %}
      <a
        class="btn btn-lg btn-light"
        href="{% url 'posts:profile_unfollow' author.username %}" role="button"
      >
        Отписаться
      </a>
    {% else %}
        <a
          class="btn btn-lg btn-primary"
          href="{% url 'posts:profile_follow' author.username %}" role="button"
        >
          Подписаться
        </a>  
    {% endif %}
  </div> 
  {% for post in page_obj %}
    <article> 
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.created|date:"d E Y" }}
        </li>
      </ul>
      {% thumbnail post.image "960x339" crop="30%" upscale=True as im %}
      <img class="card-img my-2" src="{{ im.url }}">
      {% endthumbnail %}  
      <p>
        {{ post.text }}
        {{ post.id }}            
      </p>
      <a href="{% url 'posts:post_detail' post.id %}">
        Подробная информация 
      </a> 
      <p> 
      </p>  
      {% if post.group %}
      <a href="{% url 'posts:group_list' post.group.slug %}">
        Все записи группы
      </a>
    {% endif %}
    <article>
    <hr>
  {% endfor %}
  {% include 'posts/includes/paginator.html' %}
</div>
{% if not forloop.last %} <hr> {% endif %}
{% endblock %}